theme: jekyll-theme-cayman

# Tell Jekyll to explicitly ignore these folders so they don't crash the build
exclude:
  - tests/
  - schemas/
  - reference-parsers/
  - mock_data/
  - userdata/
  - "*.urmproj"
