theme: jekyll-theme-cayman

# Tell Jekyll to explicitly ignore these folders so they don't crash the build
exclude:
  - tests/
  - schemas/
  - tools/
  - samples/
  - utilities/
  - clearinghouse/
  - RFCs/
  - reference-parsers/
  - mock_data/
  - userdata/
  - "*.urmproj"
